version: "2"

services:
  nginx:
    build: ./nginx
    image: chainify/alexa-nginx
    container_name: alexa-nginx
    ports:
      - 190:80
      - 3003:3003
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - api
      - parser
      - ipfs
      - postgres
      - sponsor
    networks:
      internal:
        ipv4_address: 10.9.0.2
    restart: unless-stopped

  web:
    build: ./web
    image: chainify/alexa-web
    container_name: alexa-web
    volumes:
      - ./web:/opt
    environment:
      - CDM_VERSION=${CDM_VERSION}
      - ASSET_ID=${ASSET_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CLIENT_PREFIX=${CLIENT_PREFIX}
      - API_HOST=${API_HOST}
      - NETWORK=${NETWORK}
      - WS_PORT=${WS_PORT}
      - SPONSOR_HOST=${SPONSOR_HOST}
      - CLIENT_SEED=${CLIENT_SEED}
      - ROOT_SEED=${ROOT_SEED}
    restart: unless-stopped
    networks:
      internal:
        ipv4_address: 10.9.0.3
    command: bash -c "npm install -y && npm run dev"

  api:
    build: ./server
    image: chainify/alexa-api
    container_name: alexa-api
    volumes:
      - ./server:/opt
    environment:
      - SPONSOR_SEED=${SPONSOR_SEED}
      - ENV=${ENV}
      - CDM_VERSION=${CDM_VERSION}
      - API_VERSION=${API_VERSION}
      - ORIGINS=${ORIGINS}
      - ASSET_ID=${ASSET_ID}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SPONSOR_PUBLIC_KEY=${SPONSOR_PUBLIC_KEY}
      - NODE_URL=${NODE_URL}
    depends_on:
      - ipfs
      - postgres
    tty: true
    stdin_open: true
    networks:
      internal:
        ipv4_address: 10.9.0.4
    restart: unless-stopped
    command: bash -c "python3.7 server.py"

  parser:
    build: ./parser
    image: chainify/alexa-parser
    container_name: alexa-parser
    volumes:
      - ./parser:/opt
    depends_on:
      - postgres
      - ipfs
    environment:
      - ENV=${ENV}
      - CDM_VERSION=${CDM_VERSION}
      - ASSET_ID=${ASSET_ID}
      - NODE_URL=${NODE_URL}
      - START_HEIGHT=${START_HEIGHT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: bash -c "python3.7 server.py"
    tty: true
    stdin_open: true
    networks:
      internal:
        ipv4_address: 10.9.0.5
    labels:
      - "autoheal=true"
    restart: unless-stopped

  postgres:
    build: ./postgresql
    image: chainify/alexa-postgres
    container_name: alexa-postgres
    volumes:
      - ~/.data/alexa/postgres:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    tty: true
    stdin_open: true
    networks:
      internal:
        ipv4_address: 10.9.0.6
    restart: unless-stopped

  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: alexa-ipfs
    volumes:
      - ~/.data/alexa/ipfs/data:/data/ipfs
      - ~/.data/alexa/ipfs/staging:/export
    ports:
      - 4011:4001
      - 5011:5001
      - 8090:8080
    networks:
      internal:
        ipv4_address: 10.9.0.7
    tty: true
    stdin_open: true
    restart: unless-stopped

  autoheal:
    image: willfarrell/autoheal:latest
    container_name: alexa-autoheal
    restart: always
    networks:
      internal:
        ipv4_address: 10.9.0.8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal

  sponsor:
    build: ./sponsor
    image: chainify/alexa-sponsor
    container_name: alexa-sponsor
    volumes:
      - ./sponsor:/usr/src/app
    environment:
      - SPONSOR_SEED=${SPONSOR_SEED}
      - CLIENT_PUBLIC_KEY=${CLIENT_PUBLIC_KEY}
      - ASSET_ID=${ASSET_ID}
      - NETWORK=${NETWORK}
      - NODE_URL=${NODE_URL}
      - CLIENT_PREFIX=${CLIENT_PREFIX}
      - CDM_VERSION=${CDM_VERSION}
      - API_HOST=${API_HOST}
    networks:
      internal:
        ipv4_address: 10.9.0.9
    tty: true
    stdin_open: true
    restart: unless-stopped
    command: bash -c "npm install -y && node server.js"
    

networks:
  internal:
    driver: bridge
    ipam:
     config:
       - subnet: 10.9.0.0/16